title: "Teknobabbel"
description: "Viggo Tellefsen Wivestad"
theme: minima
timezone: Europe/Oslo
url: "https://teknobabbel.no"
baseurl: ""

# Pages in the top navigation
header_pages:
  - index.md
  - writing_popular.md
  - courses.md
  - contact.md

# Keep clean URLs
permalink: /:categories/:title/

# Build settings
collections:
  links:
    output: true
permalink: /:year/:month/:day/:title/
