title: "Teknobabbel"
description: "Viggo Tellefsen Wivestad"
theme: minima

# Pages in the top navigation
header_pages:
  - index.md
  - writing_popular.md
  - courses.md
  - contact.md

# Keep clean URLs
permalink: /:categories/:title/

# Build settings
collections:
  links:
    output: false   # only render links in the Writing list
permalink: /:year/:month/:day/:title/
