title: "Teknobabbel"
description: "Teknobabbel - teknologi, vitenskap, formidling og samfunn"
author: "Viggo Tellefsen Wivestad"
theme: minima
timezone: Europe/Oslo
url: "https://teknobabbel.no"
baseurl: ""

# Markdown engine
markdown: kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  footnote_backlink: "&#8617;"

# Pages in the top navigation
header_pages:
  - index.md
  - writing_popular.md
  - writing_academic.md
  - courses.md
  - achievements.md
  - contact.md

# Build settings
collections:
  links:
    output: true
  publications:
    output: true
  courses:
    output: true
    permalink: /courses/:name/
  achievements:
    output: false

permalink: /:year/:month/:day/:title/
